<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,2,1,'5Lqn5ZOB5bGV56S6');
$cfg_Cs[2]=array(0,1,1,'5paw6Ze75Lit5b+D');
$cfg_Cs[4]=array(1,2,1,'572R56uZ6K6+6K6h');
$cfg_Cs[5]=array(1,2,1,'5omL5py65bqU55So');
$cfg_Cs[6]=array(1,2,1,'5bmz6Z2i6K6+6K6h');
$cfg_Cs[7]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[8]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[9]=array(2,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[10]=array(2,1,1,'6KGM5Lia5paw6Ze7');
$cfg_Cs[11]=array(2,1,1,'5pyA5paw5Yqo5oCB');
$cfg_Cs[13]=array(0,1,1,'5pyN5Yqh5Lit5b+D');
?>