<?php
$z[0]=Array("field","",445,464);
$z[0][4]['name']="title";
$z[1]=Array("global","",465,491);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",532,561);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",601,659);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3210,3245);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",23047,23084);
$z[5][4]['filename']="footer.htm";

?>