<?php
$z[0]=Array("arclist","\r\n            <div class=\"blog-post\"> <span class=\"post-meta\">[field:pubdate function=MyDate('Y-m-d',@me)'/]</span> <a class=\"post-title\" href=\"[field:arcurl /]\">[field:title/]</a>\r\n              <p> [field:infos /] </p>\r\n            </div>\r\n            ",917,1246);
$z[0][4]['titlelen']="40";
$z[0][4]['row']="2";
$z[0][4]['typeid']="9";
$z[0][4]['infolen']="40";
$z[1]=Array("global","",1549,1575);
$z[1][4]['name']="moke_adress";
$z[2]=Array("global","",1639,1659);
$z[2][4]['name']="phone";
$z[3]=Array("global","",1721,1741);
$z[3][4]['name']="email";
$z[4]=Array("global","",1804,1828);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",3964,3990);
$z[5][4]['name']="cfg_powerby";

?>