<?php
$z[0]=Array("field","",445,464);
$z[0][4]['name']="title";
$z[1]=Array("global","",465,491);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",532,561);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",601,659);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3210,3245);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",3551,3581);
$z[5][4]['name']="typename";
$z[6]=Array("field","",3710,3739);
$z[6][4]['name']="position";
$z[7]=Array("arclist","\r\n				<div class=\"accordion accordion-active\">\r\n					<div class=\"accordion-header\">\r\n						<div class=\"accordion-icon\">\r\n						</div>\r\n						<h5>[field:title/]</h5>\r\n					</div>\r\n					<div class=\"accordion-content display-block\">\r\n						<p>\r\n							[field:infos /]...<a href=\"[field:arcurl /]\" target=\"_blank\">[详情]</a>\r\n						</p>\r\n						\r\n					</div>\r\n				</div>\r\n			 ",13932,14386);
$z[7][4]['titlelen']="100";
$z[7][4]['limit']="0,1";
$z[7][4]['typeid']="4";
$z[7][4]['infolen']="220";
$z[8]=Array("arclist","\r\n				<div class=\"accordion\">\r\n					<div class=\"accordion-header\">\r\n						<div class=\"accordion-icon\">\r\n						</div>\r\n						<h5>[field:title/]</h5>\r\n					</div>\r\n					<div class=\"accordion-content display-block\">\r\n						<p>\r\n							[field:infos /]...<a href=\"[field:arcurl /]\" target=\"_blank\">[详情]</a>\r\n						</p>\r\n						\r\n					</div>\r\n				</div>\r\n			 ",14402,14839);
$z[8][4]['titlelen']="100";
$z[8][4]['limit']="1,2";
$z[8][4]['typeid']="4";
$z[8][4]['infolen']="220";
$z[9]=Array("include","",16941,16978);
$z[9][4]['filename']="footer.htm";

?>